version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/infra"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
  
  - package-ecosystem: "pip"
    directory: "/lambda"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
