config:
  aws:region: us-east-1
  finops-cost-control-as-code:home_region: us-east-1
  finops-cost-control-as-code:max_free_ebs_gb: "30"
  finops-cost-control-as-code:enable_cur: "false"
  finops-cost-control-as-code:enable_anomaly_detection: "false"
  aws:profile: default
